# Generated by Django 5.1.4 on 2024-12-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhook", "0002_remove_user_id_user_booth_collection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
